multi:
  datasource:
    enable: true
    load-mode: prop
    init-db:
      default:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/iduckcoms
        driver-class-name: com.mysql.cj.jdbc.Driver
elastic-job:
  zookeeper:
    server-list: 127.0.0.1:2181
    namespace: job-syb
  load-mode: prop
  init-job:
    testJob:
      bean-name: testJob
      cron: 0/2 * * * * ?
      sharding-count: 1
      sharding-param: 0=A
      source-key: default
spring:
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/iduckcoms
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 5000
      query-timeout: 100
      transaction-query-timeout: 100